### ISSUE TITLE
bulk importer doesn't recognize controlled values translations for custom locales

### ISSUE THREAD

**Issue by rvdb** [dartmouth-dltg/aspace_custom_localizations#1]
Hi @jdshaw ,

We might be running into a side-effect: when uploading archival objects via CSV import, translations for Controlled Value Lists aren't recognized. For example, the `common/locales/enums/nl.yml` file contains:

```
    archival_record_level:
      class: Afdeling
      collection: Verzameling
      file: Bestanddeel
      fonds: Archief
      item: Object
      otherlevel: Ander niveau
      recordgrp: Archiefblok
      series: Reeks
      subfonds: Deelarchief
      subgrp: Deelgroep
      subseries: Deelreeks
```
Yet, when the CSV template is using these translations, they are rejected with following messages:

```
Row 5:	ERROR NOT FOUND: 'Deelarchief' not found in list archival_record_level; Missing valid Description Level
Row 5:	ERROR Date label [Creatie] invalid for (Date: type:range, label: Creatie, begin: 1987, end: 1989, expression: ). The date will not be processed.
Row 5:	ERROR NOT FOUND: 'Deelarchief' not found in list archival_record_level
Row 5:	ERROR Cannot validate language (Nederlands)
Row 5:	ERROR Unable to validate Extent (Extent: Geheel 5 meter  inschrijvingsnummer magazijnplaats): NOT FOUND: 'Geheel' not found in list extent_portion
Row 5:	ERROR NOT FOUND: 'Maker' not found in list linked_agent_role
Row 5:	ERROR Unable to create agent link: 'Maker' is not a valid Role
Row 6:	ERROR Archival Object would not be created
Row 6:	ERROR NOT FOUND: 'Reeks' not found in list archival_record_level; Missing valid Description Level
Row 6:	ERROR Date label [Creatie] invalid for (Date: type:single, label: Creatie, begin: 2002, end: , expression: ). The date will not be processed.
Row 6:	ERROR NOT FOUND: 'Reeks' not found in list archival_record_level
Row 6:	ERROR Cannot validate language (Frans)
Row 6:	ERROR Unable to validate Extent (Extent: Geheel 7 archiefdozen   ): NOT FOUND: 'Geheel' not found in list extent_portion
Row 7:	ERROR Archival Object would not be created
Row 7:	ERROR NOT FOUND: 'Verzameling' not found in list archival_record_level; Missing valid Description Level
Row 7:	ERROR NOT FOUND: 'Verzameling' not found in list archival_record_level
Row 7:	ERROR Cannot validate language (Zweeds)
Row 7:	ERROR Unable to validate Extent (Extent: Geheel 8 Gigabytes   ): NOT FOUND: 'Geheel' not found in list extent_portion
```
The upload does succeed, however, when the controlled values in the CSV file make use of the enum keys, instead of the values (for example, changing "Reeks" to "series" in the CSV). 

We didn't run into this behaviour when declaring our translations with the "en" language key, and `AppConfig[:locale] = :en` in config.rb.

Is there something else that needs modification to make the bulk importer work with custom locales?

Best,

Ron
